import img1 from "../src/assets/Frame 1230.png"

export const trendingCourses = [
    {
      id: 1,
      title: "The Ultimate Beginners Guide to Cloud Computer",
      image: img1,
      rating: 4.5,
      userCount: "30k+ users",
      currentPrice: 5000,
      originalPrice: 8000,
      tags: ["cloud", "intermediate"],
    },
    {
      id: 2,
      title: "The Ultimate Beginners Guide to Cloud Computer",
      image: "https://picsum.photos/600/600",
      rating: 4.8,
      userCount: "25k+ users",
      currentPrice: 5000,
      originalPrice: 8000,
      tags: ["cloud", "intermediate"],
    },
    {
      id: 3,
      title: "The Ultimate Beginners Guide to Cloud Computer",
      image: "https://picsum.photos/600",
      rating: 4.7,
      userCount: "35k+ users",
      currentPrice: 5000,
      originalPrice: 8000,
      tags: ["cloud", "intermediate"],
    },
    {
      id: 4,
      title: "The Ultimate Beginners Guide to Cloud Computer",
      image: "https://picsum.photos/200",
      rating: 4.6,
      userCount: "28k+ users",
      currentPrice: 5000,
      originalPrice: 8000,
      tags: ["cloud", "intermediate"],
    },
  ]
  
  export const topRatedCourses = [
    {
      id: 5,
      title: "The Ultimate Beginners Guide to Cloud Computer",
      image: "https://picsum.photos/300",
      rating: 5.0,
      userCount: "40k+ users",
      currentPrice: 5000,
      originalPrice: 8000,
      tags: ["cloud", "intermediate"],
    },
    {
      id: 6,
      title: "The Ultimate Beginners Guide to Cloud Computer",
      image: "https://picsum.photos/400",
      rating: 4.9,
      userCount: "32k+ users",
      currentPrice: 5000,
      originalPrice: 8000,
      tags: ["cloud", "intermediate"],
    },
    {
      id: 7,
      title: "The Ultimate Beginners Guide to Cloud Computer",
      image: "https://picsum.photos/500",
      rating: 4.8,
      userCount: "29k+ users",
      currentPrice: 5000,
      originalPrice: 8000,
      tags: ["cloud", "intermediate"],
    },
    {
      id: 8,
      title: "The Ultimate Beginners Guide to Cloud Computer",
      image: "https://picsum.photos/600",
      rating: 4.7,
      userCount: "26k+ users",
      currentPrice: 5000,
      originalPrice: 8000,
      tags: ["cloud", "intermediate"],
    },
  ]
  
  export const newCourses = [
    {
      id: 9,
      title: "The Ultimate Beginners Guide to Cloud Computer",
      image: "https://picsum.photos/200",
      rating: 4.6,
      userCount: "15k+ users",
      currentPrice: 5000,
      originalPrice: 8000,
      tags: ["cloud", "intermediate"],
    },
    {
      id: 10,
      title: "The Ultimate Beginners Guide to Cloud Computer",
      image: "https://picsum.photos/300",
      rating: 4.5,
      userCount: "12k+ users",
      currentPrice: 5000,
      originalPrice: 8000,
      tags: ["cloud", "intermediate"],
    },
    {
      id: 11,
      title: "The Ultimate Beginners Guide to Cloud Computer",
      image: "https://picsum.photos/400",
      rating: 4.4,
      userCount: "10k+ users",
      currentPrice: 5000,
      originalPrice: 8000,
      tags: ["cloud", "intermediate"],
    },
    {
      id: 12,
      title: "The Ultimate Beginners Guide to Cloud Computer",
      image: "https://picsum.photos/500",
      rating: 4.3,
      userCount: "8k+ users",
      currentPrice: 5000,
      originalPrice: 8000,
      tags: ["cloud", "intermediate"],
    },
  ]
  
  export const instructors = [
    {
      id: 1,
      name: "Nolan Matthew",
      role: "UI/UX Designer",
      courseCount: "5 Courses",
      image: "https://picsum.photos/200",
      rating: 4.8,
    },
    {
      id: 2,
      name: "Haris Mehra",
      role: "Cloud Engineer",
      courseCount: "7 Courses",
      image: "https://picsum.photos/300",
      rating: 4.9,
    },
    {
      id: 3,
      name: "Amanda Ceria",
      role: "UI/UX Designer",
      courseCount: "10 Courses",
      image: "https://picsum.photos/400",
      rating: 4.7,
    },
    {
      id: 4,
      name: "John Serie",
      role: "UI/UX Designer",
      courseCount: "8 Courses",
      image: "https://picsum.photos/500",
      rating: 4.6,
    },
  ]
  
  